[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
  ". /opt/venv/bin/activate && python -c 'import torch; print(\"PyTorch version:\", torch.__version__)'"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app:app"