[build]
builder = "dockerfile"

[deploy]
startCommand = "python app_simple.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = "5000"
